# Generated by Django 6.0.4 on 2026-05-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('VOID', 'Void')], default='PENDING', max_length=20),
        ),
    ]
